### ISSUE TITLE
Add documentation and comments for GitLab configuration for GitProvider Receiver and demo

### ISSUE THREAD

**Issue by ericchapman80** [liatrio/tag-o11y-quick-start-manifests#10]
Update the existing olly-demo solution to also work with GitLab.  For context, I would like to have the Engineering Metrics (signals from git) working at all of our GitLab customers and added to the LDM.

**Comment by adrielp** [comment]
Closing this, can re-open if it becomes an issue. Our backlog is too big and this is just not a priority. Feel free to open a new issue if you disagree & (or) make the contribution yourself next time you go through GitLab's setup.
